### ISSUE TITLE
no release tags

### ISSUE THREAD

**Issue by ljharb** [getify/literalizer#13]
Every time something's published to npm (and the version number is bumped), that SHA should be tagged with the version, like `v1.0.0`. That complies with both npm module convention, and with Github's "releases" feature.

Unfortunately I can't PR tags, or I'd do it for you :-/

**Comment by getify** [comment]
Thanks for the suggestion. I'm not terribly familiar with using tags and with the new "releases" feature. Mostly, I was thinking that's something I would start doing once there was a level of stability to the project that I had at least declared a "1.x" release.

Every new release right now is a complete replacement of the previous, for good reason, since it's under rapid flux/dev. So being able to keep around all the extra versions as "releases" and get at them individually seems to have reduced value.

FYI: I publish frequently to npm right now only because I have several other projects I'm already developing against/with literalizer, and that's the easiest way to share code between my various projects.

Once things stabilize a bit, I wouldn't be pushing to npm with every commit, and I wouldn't thus be creating a new tag 5+ times per day. :)

In any case, I will keep in mind your perfectly valid point -- the need to tag the "releases" to keep the project in a sensible and predictable state. :)
